import type { LyricLine, SongMetadata } from '../types';

export interface AEExportConfig {
  variableName?: string;
  startColorHex?: string;
  endColorHex?: string;
  glowRadius?: number;
}

/**
 * Creates a valid, clean JavaScript variable identifier
 */
export function createSafeJSIdentifier(title: string): string {
  let asciiOnly = title.replace(/[^a-zA-Z0-9]/g, '');
  if (asciiOnly.length > 0) {
    if (/^[0-9]/.test(asciiOnly)) asciiOnly = '_' + asciiOnly;
    return asciiOnly;
  }
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash = (hash << 5) - hash + title.charCodeAt(i);
    hash |= 0;
  }
  return 'Song_' + Math.abs(hash).toString(16);
}

/**
 * Universal After Effects Script Format
 * Can be used as a modular data file in MaO's songs/ repository
 * AND can be executed directly as a standalone script in Adobe After Effects.
 */
export function generateAEScript(
  lyrics: LyricLine[],
  meta: SongMetadata,
  config?: AEExportConfig
): string {
  const safeTitle = meta.title || 'Untitled Song';
  const safeArtist = meta.artist || 'Unknown Artist';

  const baseIdentifier = config?.variableName || createSafeJSIdentifier(safeTitle);
  const varName = (baseIdentifier.endsWith('Data') ? baseIdentifier : baseIdentifier + 'Data');

  const startColor = config?.startColorHex || '#ff9a9e';
  const endColor = config?.endColorHex || '#fecfef';
  const glowRadius = config?.glowRadius !== undefined ? config.glowRadius : 220;

  const linesCode = lyrics.map((line) => {
    const safeIn = Math.max(0, line.inTime);
    let safeOut = line.outTime;
    if (safeOut <= safeIn) {
      safeOut = safeIn + 3.0;
    }

    const cleanEn = JSON.stringify(line.original || '');
    const cleanTh = JSON.stringify(line.translation || line.referenceTranslation || '');
    return '        { inTime: ' + safeIn.toFixed(2) + ', outTime: ' + safeOut.toFixed(2) + ', en: ' + cleanEn + ', th: ' + cleanTh + ' }';
  }).join(',\n');

  return '/**\n' +
    ' * Universal After Effects Bilingual Karaoke Script\n' +
    ' * Song: ' + safeTitle + '\n' +
    ' * Artist: ' + safeArtist + '\n' +
    ' * Generated by Lyric Studio\n' +
    ' * Compatible with After Effects script automation and standalone execution\n' +
    ' */\n\n' +
    'var ' + varName + ' = {\n' +
    '    title: ' + JSON.stringify(safeTitle) + ',\n' +
    '    artist: ' + JSON.stringify(safeArtist) + ',\n' +
    '    options: {\n' +
    '        colors: {\n' +
    '            start: ' + JSON.stringify(startColor) + ',\n' +
    '            end: ' + JSON.stringify(endColor) + '\n' +
    '        },\n' +
    '        glow: {\n' +
    '            radius: ' + glowRadius + '\n' +
    '        }\n' +
    '    },\n' +
    '    lyrics: [\n' +
    linesCode + '\n' +
    '    ]\n' +
    '};\n\n' +
    '// Standalone Execution Handler (runs automatically if executed directly in After Effects)\n' +
    'if (typeof app !== "undefined" && app.project && app.project.activeItem && (app.project.activeItem instanceof CompItem)) {\n' +
    '    (function(data) {\n' +
    '        app.beginUndoGroup("Create Bilingual Lyrics - " + data.title);\n' +
    '        var comp = app.project.activeItem;\n' +
    '        for (var i = 0; i < data.lyrics.length; i++) {\n' +
    '            var item = data.lyrics[i];\n' +
    '            var layer = comp.layers.addText(item.en + "\\r" + item.th);\n' +
    '            layer.name = "Lyric_" + (i + 1);\n' +
    '            layer.inPoint = item.inTime;\n' +
    '            layer.outPoint = item.outTime;\n' +
    '            var op = layer.property("Opacity");\n' +
    '            if (op) {\n' +
    '                op.setValueAtTime(item.inTime, 0);\n' +
    '                op.setValueAtTime(item.inTime + 0.3, 100);\n' +
    '                op.setValueAtTime(item.outTime - 0.3, 100);\n' +
    '                op.setValueAtTime(item.outTime, 0);\n' +
    '            }\n' +
    '        }\n' +
    '        app.endUndoGroup();\n' +
    '    })(' + varName + ');\n' +
    '}\n';
}

export const generateAEStandaloneScript = generateAEScript;
